### ISSUE TITLE
Make bots use the grappling hook if reachablilities for it exist in the map's botfile

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#259]
This would make bot matches even more difficult on maps where there's a grappling hook, for example, mfspacedm2 (http://lvlworld.com/review/id:457). This should only be possible if there's grappling hook reachablilities on the map you want to play on... This map doesn't have them, however. I have a patch for the map & the mint-game.settings for baseq3 which DOES have the necessary reachabilities & cvars...
Here they are:
mfspacedm2 patch:
https://mega.nz/#!sll1yQhZ!MkRRbh0sgVBy4XA1YwFKbuOeJBojDg_8VUtleOS2XJQ
mint-game.settings patch:
https://mega.nz/#!RslyDLbJ!Twm8Fh4d4HCI6L59Y5z5hC04cUFPYLHT6_5bF117MlA

**Comment by ensiform** [comment]
You can include the diff/patch in a github comment as a code block see markdown formatting for how.

**Comment by coltongit** [comment]
it seems like you can only put in _actual_ code in there as a code block @ensiform. Other stuff, like links, doesn't really work in there.

**Comment by zturtleman** [comment]
Untested fix committed in https://github.com/zturtleman/mint-arena/commit/bf753130ced0c3b4f9501b24ae633884d9ec780d.

**Comment by coltongit** [comment]
It's best if someone tests this a little more thoroughly @zturtleman. Best thing to do if you want to make sure your fix is usable.

**Comment by mecwerks** [comment]
This is why he committed it, it built, if it doesn't work someone can say something.

**Comment by coltongit** [comment]
When I tried this on mfspacedm2 (using the linked botfile), they still don't grab the grappling hook.

**Comment by zturtleman** [comment]
You did not report that bots do you grab the grappling hook. You reported they do you use the grapple reachabilities. Grapple reachabilities are how to use the grappling hook to reach other parts of the map, not how to reach the grappling hook.

When I briefly tested mfspacedm2 I could only get the Grappling Hook using a weapon jump. Bots will only use jump pads to get suspended items.

**Comment by KuehnhammerTobias** [comment]
Heh?! MIt seems my comment vanished!
Anyways, bots + grapple works as always (regardless if with cvar or with zturtleman's changes):
![grapple_bot01](https://cloud.githubusercontent.com/assets/5429387/15748393/02cbc9d2-28df-11e6-9fe2-ee117ef62ad6.jpg)
Screenshot shows bot 'Bitterman' following me with grapple.

Agree with zturtleman:
You didn't report that bots do not grab the weapon. You wrote the bot should use the grapple. These are two different things.
USE = switch to/holding, etc.
GRAB = pick up/walk over etc.
So, your problem is because of why zturtleman said: because grapple is only reachable with a rocketjump.

**Comment by coltongit** [comment]
Maybe having the bots use weapon jumps to grab weapons as well would most likely get them to grab the grappling hook @zturtleman.

**Comment by zturtleman** [comment]
@coltongit please stay on topic and don't use the issue tracker as a discussion board. Only create issues for Spearmint errors, not feature requests or bot AI improvement ideas.

**Comment by coltongit** [comment]
As I said earlier, shouldn't the bots _already_ be able to weapon jump to other weapons @zturtleman?

**Comment by KuehnhammerTobias** [comment]
@coltongit: zturtleman alread said that bots will only use jump pads to get suspended items.
So,... if you don't believe it, simply have a look, it's also mentioned in the Radiant manual:
[_"...keep in mind that when a suspended item is not anywhere near the ground the bot will ONLY try to go for this suspended item using jump pads."_](https://icculus.org/gtkradiant/documentation/q3radiant_manual/appndx/appn_c.htm).

**Comment by coltongit** [comment]
Since this already works, & zturtleman's changes enable this by default, I'll go ahead & close this.
